# Generated by Django 3.1.3 on 2020-11-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.CharField(max_length=600),
        ),
    ]
